import 'fake-indexeddb/auto';
import { afterEach, describe, expect, it } from 'vitest';
import { readFileSync } from 'node:fs';
import { parseProducts, newEditor, quoteNumber, todayDubai } from '../lib/model';
import { billableWeight, calculate } from '../lib/calculations';
import { renderQuote } from '../lib/render';
import { db, saveQuote, nextSerial, markSent, exportBackup, parseBackup, restoreBackup, serialWarning } from '../lib/storage';
const product={part_number:'S-T50',manufacturer:'Mitsubishi Electric',description:'Industrial contactor',quantity:2,unit_weight_kg:0.4,weight_type:'net',weight_source_type:'manufacturer',weight_source_url:null,datasheet_url:'https://example.com/item?x=1&y=2',document_type:'product_page',product_status:'active',verification_notes:null};
const data=()=>parseProducts(JSON.stringify({schema_version:'1.0',products:[product]}));
const editor=()=>{const e=newEditor(data(),1);e.date='2026-09-22';e.products[0].price='100';e.products[0].leadTime='1 week';return e;};
afterEach(async()=>{await db.quotes.clear();await db.used.clear();await db.settings.clear();});
describe('Imports and quotation identity',()=>{
 it('preserves order, exact part numbers, duplicates and null fields',()=>{const d=parseProducts(JSON.stringify({schema_version:'1.0',products:[product,{...product,part_number:'  A-01/ß ',unit_weight_kg:null},product]}));expect(d.products.map(p=>p.part_number)).toEqual(['S-T50','  A-01/ß ','S-T50']);expect(d.products[1].unit_weight_kg).toBeNull();});
 it('rejects malformed JSON and invalid schema with useful errors',()=>{expect(()=>parseProducts('{')).toThrow('Invalid JSON');expect(()=>parseProducts('{"schema_version":"2.0","products":[]}')).toThrow('schema_version');});
 it('rejects unsafe links',()=>{expect(()=>parseProducts(JSON.stringify({schema_version:'1.0',products:[{...product,datasheet_url:'javascript:alert(1)'}]}))).toThrow('http');});
 it('generates exact numbers and changes only with serial/date',()=>{expect(quoteNumber('2026-09-22','3')).toBe('Q-ENCR26-S3-2209');expect(quoteNumber('2027-01-02','5')).toBe('Q-ENCR27-S5-0201');for(const s of ['0','-1','1.2','a','01'])expect(()=>quoteNumber('2026-09-22',s)).toThrow();expect(()=>quoteNumber('2026-02-30','1')).toThrow();expect(todayDubai()).toMatch(/^\d{4}-\d{2}-\d{2}$/);});
});
describe('Decimal-safe calculations',()=>{
 it.each([['0.10','0.5'],['0.40','0.5'],['0.50','0.5'],['0.55','1'],['0.75','1'],['1.00','1'],['1.10','1.5'],['1.60','2']])('rounds %s kg to %s kg', (a,b)=>expect(billableWeight(a).toString()).toBe(b));
 it('matches the specified example and never compounds shipping',()=>{const e=editor();const t=calculate(e);expect(t.rows[0]).toMatchObject({rate:'3.7',shipping:'15.00',totalShipping:'30.00',unit:'385.00',total:'770.00'});expect(t).toMatchObject({subtotal:'770.00',vat:'38.50',grandTotal:'808.50'});expect(calculate(e)).toEqual(t);});
 it('rounds unit prices before multiplying and rounds VAT',()=>{const e=editor();e.products[0].price='0.005';e.products[0].currency='AED';e.products[0].quantity=3;expect(calculate(e)).toMatchObject({subtotal:'45.03',vat:'2.25',grandTotal:'47.28'});});
 it('requires positive weights and configured EUR/GBP rates',()=>{const e=editor();e.products[0].weight='';expect(()=>calculate(e)).toThrow('weight');e.products[0].weight='0';expect(()=>calculate(e)).toThrow('greater than zero');e.products[0].weight='0.4';e.products[0].currency='EUR';expect(()=>calculate(e)).toThrow('EUR exchange rate');});
 it('supports independent currencies with consistent manual rates',()=>{const e=editor();e.rates={EUR:'4',GBP:'5'};e.products=['USD','EUR','GBP','AED'].map(c=>({...e.products[0],currency:c as 'USD',quantity:1}));expect(calculate(e).rows.map(r=>r.unit)).toEqual(['385.00','415.00','515.00','115.00']);});
});
describe('Template fidelity and injection safety',()=>{
 it('preserves the template styles, merged cells and exact conditions',()=>{const original=readFileSync('reference/original-template.html','utf8');const e=editor();const html=renderQuote(e,calculate(e));const notes=[...original.matchAll(/<td colspan="4"[^>]*>(.*?)<\/td>/g)].map(m=>m[1]);for(const note of notes)expect(html).toContain(note);expect(html).toContain('table-layout:fixed');expect(html).toContain('border:1px solid #777;padding:7px;vertical-align:top;');expect(html).not.toContain('Best regards');expect(html).not.toContain('MW Group');});
 it('escapes all dynamic text and preserves exact URLs as encoded attributes',()=>{const e=editor();e.customer='<script>alert(1)</script>';e.products[0].description='<img src=x onerror=alert(1)>';const html=renderQuote(e,calculate(e));expect(html).not.toContain('<script>');expect(html).not.toContain('<img');expect(html).toContain('https://example.com/item?x=1&amp;y=2');expect(html).not.toContain('verification_notes');e.products[0].datasheet_url=null;expect(renderQuote(e)).not.toContain('<a ');});
});
describe('IndexedDB, status, serial ledger and backups',()=>{
 it('persists complete drafts, edits with the same number and actual Sent timestamp',async()=>{const e=editor();const q=await saveQuote(e,data());expect((await db.quotes.get(q.id))?.status).toBe('Draft');expect((await saveQuote(e,data(),q.id)).number).toBe(q.number);await expect(markSent(q.id)).rejects.toThrow('customer');e.customer='Customer';await saveQuote(e,data(),q.id);await markSent(q.id);const sent=await db.quotes.get(q.id);expect(sent?.status).toBe('Sent');expect(sent?.sentAt).toBeTruthy();});
 it('prevents concurrent duplicates and never recycles deleted numbers',async()=>{const e=editor();e.serial='8';const results=await Promise.allSettled([saveQuote(e,data()),saveQuote(e,data())]);expect(results.filter(r=>r.status==='fulfilled')).toHaveLength(1);expect(await nextSerial(2026)).toBe(9);await db.quotes.clear();expect(await nextSerial(2026)).toBe(9);await expect(saveQuote(e,data())).rejects.toThrow('reserved');e.date='2026-09-23';expect(await serialWarning(e)).toBe(true);await saveQuote(e,data());});
 it('exports and restores complete data including deleted reservations',async()=>{const e=editor();const q=await saveQuote(e,data());e.serial='2';const removed=await saveQuote(e,data());await db.quotes.delete(removed.id);const b=parseBackup(JSON.stringify(await exportBackup()));await restoreBackup(b,true);expect((await db.quotes.get(q.id))?.html).toBe(q.html);expect(await nextSerial(2026)).toBe(3);await restoreBackup(b,false);expect(await db.quotes.count()).toBe(1);});
 it('merges an unchanged exported backup before any replacement',async()=>{await saveQuote(editor(),data());const b=parseBackup(JSON.stringify(await exportBackup()));await restoreBackup(b,false);expect(await db.quotes.count()).toBe(1);});
 it('rejects tampered HTML and totals and rolls back merge conflicts',async()=>{const q=await saveQuote(editor(),data());const b=await exportBackup();const bad=structuredClone(b);bad.quotes[0].html+='<script>alert(1)</script>';expect(()=>parseBackup(JSON.stringify(bad))).toThrow();const e=editor();e.customer='Changed';await saveQuote(e,data(),q.id);await expect(restoreBackup(b,false)).rejects.toThrow('conflict');expect((await db.quotes.get(q.id))?.editor.customer).toBe('Changed');});
});
