import 'fake-indexeddb/auto';
import { afterEach, describe, expect, it } from 'vitest';
import { readFileSync } from 'node:fs';
import Dexie from 'dexie';
import { defaultRates, normalizeEditor, parseProducts, newEditor, quoteNumber, todayDubai } from '../lib/model';
import { billableWeight, calculate, removeProduct } from '../lib/calculations';
import { renderQuote } from '../lib/render';
import { QuoteDB, db, saveQuote, nextSerial, markSent, exportBackup, loadRates, parseBackup, restoreBackup, saveRates, serialWarning } from '../lib/storage';
const product={part_number:'S-T50',manufacturer:'Mitsubishi Electric',description:'Industrial contactor',quantity:2,unit_weight_kg:0.4,weight_type:'net',weight_source_type:'manufacturer',weight_source_url:null,datasheet_url:'https://example.com/item?x=1&y=2',document_type:'product_page',product_status:'active',verification_notes:null};
const data=()=>parseProducts(JSON.stringify({schema_version:'1.0',products:[product]}));
const editor=()=>{const e=newEditor(data(),1);e.date='2026-09-22';e.products[0].price='100';e.products[0].leadTime='1 week';return e;};
afterEach(async()=>{await db.quotes.clear();await db.used.clear();await db.settings.clear();});
describe('Imports and quotation identity',()=>{
 it('preserves order, exact part numbers, duplicates and null fields',()=>{const d=parseProducts(JSON.stringify({schema_version:'1.0',products:[product,{...product,part_number:'  A-01/ß ',unit_weight_kg:null},product]}));expect(d.products.map(p=>p.part_number)).toEqual(['S-T50','  A-01/ß ','S-T50']);expect(d.products[1].unit_weight_kg).toBeNull();});
 it('rejects malformed JSON and invalid schema with useful errors',()=>{expect(()=>parseProducts('{')).toThrow('Invalid JSON');expect(()=>parseProducts('{"schema_version":"2.0","products":[]}')).toThrow('schema_version');});
 it('rejects unsafe links',()=>{expect(()=>parseProducts(JSON.stringify({schema_version:'1.0',products:[{...product,datasheet_url:'javascript:alert(1)'}]}))).toThrow('http');});
 it('generates exact numbers and changes only with serial/date',()=>{expect(quoteNumber('2026-09-22','3')).toBe('Q-ENCR26-S3-2209');expect(quoteNumber('2027-01-02','5')).toBe('Q-ENCR27-S5-0201');for(const s of ['0','-1','1.2','a','01'])expect(()=>quoteNumber('2026-09-22',s)).toThrow();expect(()=>quoteNumber('2026-02-30','1')).toThrow();expect(todayDubai()).toMatch(/^\d{4}-\d{2}-\d{2}$/);});
});
describe('Decimal-safe calculations',()=>{
 it.each([['0.10','0.5'],['0.40','0.5'],['0.50','0.5'],['0.55','1'],['0.75','1'],['1.00','1'],['1.10','1.5'],['1.60','2']])('rounds %s kg to %s kg', (a,b)=>expect(billableWeight(a).toString()).toBe(b));
 it('matches the specified example and never compounds shipping',()=>{const e=editor();const t=calculate(e);expect(t.rows[0]).toMatchObject({rate:'3.7',shipping:'15.00',totalShipping:'30.00',unit:'385.00',total:'770.00'});expect(t).toMatchObject({subtotal:'770.00',vat:'38.50',grandTotal:'808.50'});expect(calculate(e)).toEqual(t);});
 it('applies margin before conversion, then adds shipping',()=>{const e=editor();e.products[0].margin='15';const t=calculate(e);expect(t.rows[0]).toMatchObject({entered:'100.00',margin:'15',priceAfterMargin:'115.00',rate:'3.7',converted:'425.50',shipping:'15.00',unit:'440.50',total:'881.00'});expect(t).toMatchObject({subtotal:'881.00',vat:'44.05',grandTotal:'925.05'});});
 it('accepts 0% and decimal margins without compounding',()=>{const e=editor();e.products[0].margin='0';expect(calculate(e).rows[0].priceAfterMargin).toBe('100.00');e.products[0].margin='12.5';const first=calculate(e);expect(first.rows[0]).toMatchObject({priceAfterMargin:'112.50',converted:'416.25',shipping:'15.00',unit:'431.25',total:'862.50'});expect(first.vat).toBe('43.13');expect(calculate(e)).toEqual(first);});
 it('rejects negative and invalid margins while treating an empty margin as zero',()=>{const e=editor();e.products[0].margin='';expect(calculate(e).rows[0].margin).toBe('0');for(const margin of ['-1','NaN','Infinity','abc']){e.products[0].margin=margin;expect(()=>calculate(e)).toThrow('Margin');}});
 it('rounds unit prices before multiplying and rounds VAT',()=>{const e=editor();e.products[0].price='0.005';e.products[0].currency='AED';e.products[0].quantity=3;expect(calculate(e)).toMatchObject({subtotal:'45.03',vat:'2.25',grandTotal:'47.28'});});
 it('requires positive weights and valid configured foreign rates',()=>{const e=editor();e.products[0].weight='';expect(()=>calculate(e)).toThrow('weight');e.products[0].weight='0';expect(()=>calculate(e)).toThrow('greater than zero');e.products[0].weight='0.4';e.products[0].currency='EUR';e.rates.EUR='';expect(()=>calculate(e)).toThrow('EUR exchange rate');});
 it('provides defaults and supports editing every foreign currency',()=>{const e=editor();expect(e.rates).toEqual(defaultRates);e.rates={USD:'3.72',EUR:'4.35',GBP:'4.95'};e.products=['USD','EUR','GBP','AED'].map(c=>({...e.products[0],currency:c as 'USD',quantity:1}));const rows=calculate(e).rows;expect(rows.map(r=>r.rate)).toEqual(['3.72','4.35','4.95','1']);expect(rows.map(r=>r.unit)).toEqual(['387.00','450.00','510.00','115.00']);});
});
describe('Product removal',()=>{
 it('removes a product from totals and HTML and renumbers remaining rows',()=>{const e=editor();e.products=[{...e.products[0],part_number:'A',quantity:1},{...e.products[0],part_number:'B',quantity:1},{...e.products[0],part_number:'C',quantity:1}];const before=calculate(e);const afterEditor=removeProduct(e,1);const after=calculate(afterEditor);const html=renderQuote(afterEditor,after);expect(before.subtotal).toBe('1155.00');expect(after.subtotal).toBe('770.00');expect(html).not.toContain(' | B<');expect(html).toMatch(/>2<\/td><td colspan="3"[^>]*>.*\| C/);expect(html).not.toMatch(/>3<\/td><td colspan="3"/);});
 it('does not allow removal of the final product',()=>expect(()=>removeProduct(editor(),0)).toThrow('at least one product'));
});
describe('Template fidelity and injection safety',()=>{
 it('preserves the template styles, merged cells and exact conditions',()=>{const original=readFileSync('reference/original-template.html','utf8');const e=editor();const html=renderQuote(e,calculate(e));const notes=[...original.matchAll(/<td colspan="4"[^>]*>(.*?)<\/td>/g)].map(m=>m[1]);for(const note of notes)expect(html).toContain(note);expect(html).toContain('table-layout:fixed');expect(html).toContain('border:1px solid #777;padding:7px;vertical-align:top;');expect(html).not.toContain('Best regards');expect(html).not.toContain('MW Group');});
 it('keeps margin and all internal pricing details out of customer HTML',()=>{const e=editor();e.products[0].margin='15';const html=renderQuote(e,calculate(e));expect(html).toContain('440.50');for(const internal of ['Margin','115.00 USD','425.50','Purchase price','Exchange Rate','Shipping / Unit'])expect(html).not.toContain(internal);});
 it('escapes all dynamic text and preserves exact URLs as encoded attributes',()=>{const e=editor();e.customer='<script>alert(1)</script>';e.products[0].description='<img src=x onerror=alert(1)>';const html=renderQuote(e,calculate(e));expect(html).not.toContain('<script>');expect(html).not.toContain('<img');expect(html).toContain('https://example.com/item?x=1&amp;y=2');expect(html).not.toContain('verification_notes');e.products[0].datasheet_url=null;expect(renderQuote(e)).not.toContain('<a ');});
});
describe('IndexedDB, status, serial ledger and backups',()=>{
 it('persists editable exchange-rate preferences locally',async()=>{expect(await loadRates()).toEqual(defaultRates);await saveRates({USD:'3.72',EUR:'4.35',GBP:'4.95'});expect(await loadRates()).toEqual({USD:'3.72',EUR:'4.35',GBP:'4.95'});await db.settings.put({key:'rates',value:{USD:'',EUR:'',GBP:''}});expect(await loadRates()).toEqual(defaultRates);});
 it('persists complete drafts, edits with the same number and actual Sent timestamp',async()=>{const e=editor();const q=await saveQuote(e,data());expect((await db.quotes.get(q.id))?.status).toBe('Draft');expect((await saveQuote(e,data(),q.id)).number).toBe(q.number);await expect(markSent(q.id)).rejects.toThrow('customer');e.customer='Customer';await saveQuote(e,data(),q.id);await markSent(q.id);const sent=await db.quotes.get(q.id);expect(sent?.status).toBe('Sent');expect(sent?.sentAt).toBeTruthy();});
 it('snapshots margins and exchange rates independently of later preferences',async()=>{const e=editor();e.products[0].margin='15';e.rates.USD='3.70';const q=await saveQuote(e,data());await saveRates({USD:'3.75',EUR:'4.40',GBP:'5.00'});await saveQuote(e,data(),q.id);const saved=await db.quotes.get(q.id);expect(saved?.editor.products[0].margin).toBe('15');expect(saved?.editor.rates.USD).toBe('3.70');expect(saved?.totals.rows[0].converted).toBe('425.50');expect((await loadRates()).USD).toBe('3.75');});
 it('prevents concurrent duplicates and never recycles deleted numbers',async()=>{const e=editor();e.serial='8';const results=await Promise.allSettled([saveQuote(e,data()),saveQuote(e,data())]);expect(results.filter(r=>r.status==='fulfilled')).toHaveLength(1);expect(await nextSerial(2026)).toBe(9);await db.quotes.clear();expect(await nextSerial(2026)).toBe(9);await expect(saveQuote(e,data())).rejects.toThrow('reserved');e.date='2026-09-23';expect(await serialWarning(e)).toBe(true);await saveQuote(e,data());});
 it('exports and restores complete data including deleted reservations',async()=>{const e=editor();const q=await saveQuote(e,data());e.serial='2';const removed=await saveQuote(e,data());await db.quotes.delete(removed.id);const b=parseBackup(JSON.stringify(await exportBackup()));await restoreBackup(b,true);expect((await db.quotes.get(q.id))?.html).toBe(q.html);expect(await nextSerial(2026)).toBe(3);await restoreBackup(b,false);expect(await db.quotes.count()).toBe(1);});
 it('merges an unchanged exported backup before any replacement',async()=>{await saveQuote(editor(),data());const b=parseBackup(JSON.stringify(await exportBackup()));await restoreBackup(b,false);expect(await db.quotes.count()).toBe(1);});
 it('rejects tampered HTML and totals and rolls back merge conflicts',async()=>{const q=await saveQuote(editor(),data());const b=await exportBackup();const bad=structuredClone(b);bad.quotes[0].html+='<script>alert(1)</script>';expect(()=>parseBackup(JSON.stringify(bad))).toThrow();const e=editor();e.customer='Changed';await saveQuote(e,data(),q.id);await expect(restoreBackup(b,false)).rejects.toThrow('conflict');expect((await db.quotes.get(q.id))?.editor.customer).toBe('Changed');});
 it('imports legacy backups without margin or USD settings as 0% and 3.70',async()=>{await saveQuote(editor(),data());await saveRates(defaultRates);const legacy:any=await exportBackup();delete legacy.quotes[0].editor.products[0].margin;delete legacy.quotes[0].editor.rates.USD;delete legacy.settings[0].value.USD;delete legacy.quotes[0].totals.rows[0].entered;delete legacy.quotes[0].totals.rows[0].margin;delete legacy.quotes[0].totals.rows[0].priceAfterMargin;const parsed=parseBackup(JSON.stringify(legacy));expect(parsed.quotes[0].editor.products[0].margin).toBe('0');expect(parsed.quotes[0].editor.rates.USD).toBe('3.70');expect(parsed.settings[0].value.USD).toBe('3.70');});
 it('normalizes legacy quotation editor data without changing valid values',()=>{const legacy:any=editor();delete legacy.products[0].margin;delete legacy.rates.USD;const normalized=normalizeEditor(legacy);expect(normalized.products[0].margin).toBe('0');expect(normalized.rates.USD).toBe('3.70');});
 it('migrates existing IndexedDB quotations and settings in place',async()=>{const source=await saveQuote(editor(),data());const raw:any=structuredClone(source);delete raw.editor.products[0].margin;delete raw.editor.rates.USD;const name=`Sajith-Quote-legacy-${crypto.randomUUID()}`;const legacy=new Dexie(name);legacy.version(1).stores({quotes:'id,&number,createdAt',used:'number,year,serial,owner',settings:'key'});await legacy.open();await legacy.table('quotes').put(raw);await legacy.table('settings').put({key:'rates',value:{EUR:'4.30',GBP:'4.90'}});legacy.close();const migrated=new QuoteDB(name);const quote=await migrated.quotes.get(source.id);const settings=await migrated.settings.get('rates');expect(quote?.editor.products[0].margin).toBe('0');expect(quote?.editor.rates.USD).toBe('3.70');expect(settings?.value).toEqual(defaultRates);migrated.close();await Dexie.delete(name);});
});
