'use client';
import { useEffect, useState } from 'react';
import { Editor, Imported, currencies, newEditor, parseProducts, quoteNumber, todayDubai } from '@/lib/model';
import { calculate, calculateRow, removeProduct } from '@/lib/calculations';
import { renderQuote } from '@/lib/render';
import { assertAvailable, db, loadRates, nextSerial, saveQuote, saveRates, serialWarning } from '@/lib/storage';
import { copyQuote, download } from '@/lib/clipboard';
import Preview from './Preview';

function Field({label,value,onChange,type='text',hint,min,step}:{label:string;value:string;onChange:(s:string)=>void;type?:string;hint?:string;min?:string;step?:string}) { return <label className="field"><span>{label}</span><input aria-label={label} aria-invalid={label === "Unit Weight (kg)" && !value ? true : undefined} type={type} min={min} step={step} value={value} onChange={e=>onChange(e.target.value)}/>{hint && <small>{hint}</small>}</label>; }
export default function Generator() {
 const [text,setText]=useState(''); const [editor,setEditor]=useState<Editor|null>(null); const [original,setOriginal]=useState<Imported|null>(null); const [id,setId]=useState<string>(); const [html,setHtml]=useState(''); const [finalized,setFinalized]=useState(''); const [error,setError]=useState(''); const [message,setMessage]=useState(''); const [warning,setWarning]=useState(false); const [busy,setBusy]=useState(false); const [manualSerial,setManualSerial]=useState(false); const [ready,setReady]=useState(false);
 const fresh=!!editor && finalized===JSON.stringify(editor);
 useEffect(()=>{ let active=true; (async()=>{ try { const editId=new URLSearchParams(window.location.search).get('edit'); if(editId) { const q=await db.quotes.get(editId); if(!q) throw new Error('Saved quotation not found.'); if(active) {setEditor(q.editor);setOriginal(q.original);setId(q.id);setHtml(q.html);setFinalized(JSON.stringify(q.editor));setManualSerial(true);} } if(active)setReady(true); }catch(e){if(active){setError((e as Error).message);setReady(true);}} })(); return ()=>{active=false;}; },[]);
 useEffect(()=>{ if(!editor)return; let active=true; serialWarning(editor,id).then(v=>{if(active)setWarning(v);}).catch(e=>setError((e as Error).message)); return ()=>{active=false;}; },[editor,id]);
 useEffect(()=>{ if(!editor || fresh)return; const handler=(event:BeforeUnloadEvent)=>{event.preventDefault();}; window.addEventListener('beforeunload',handler); return ()=>window.removeEventListener('beforeunload',handler); },[editor,fresh]);
 async function run(fn:()=>Promise<void>) {setBusy(true);setError('');setMessage('');try{await fn();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 function change<K extends keyof Editor>(key:K,value:Editor[K]) {setEditor(e=>e?{...e,[key]:value}:e);setMessage('');}
 function product(index:number,key:string,value:string|null) {setEditor(e=>e?{...e,products:e.products.map((p,i)=>i===index?{...p,[key]:value}:p)}:e);setMessage('');}
 function remove(index:number) { if(!editor)return; if(editor.products.length<=1){setError('A quotation must contain at least one product.');return;} const part=editor.products[index].part_number;if(!confirm(`Remove ${part} from this quotation?`))return;const next=removeProduct(editor,index);setEditor(next);setOriginal(current=>current?{...current,products:current.products.filter((_,i)=>i!==index)}:current);try{setHtml(renderQuote(next,calculate(next)));}catch{setHtml(renderQuote(next));}setError('');setMessage(`Removed ${part}. Click Modify Template to finalize the updated quotation.`); }
 async function importData() { const data=parseProducts(text);const rates=await loadRates(); const e=newEditor(data,await nextSerial(Number(todayDubai().slice(0,4))),rates);setOriginal(data);setEditor(e);setId(undefined);setFinalized('');setHtml(renderQuote(e));setManualSerial(false); }
 async function changeDate(date:string) { if(!editor)return; const oldYear=editor.date.slice(0,4); change('date',date); if(!id && !manualSerial && date.slice(0,4)!==oldYear && /^\d{4}-\d{2}-\d{2}$/.test(date)) {const serial=await nextSerial(Number(date.slice(0,4)));setEditor(e=>e && e.date===date?{...e,serial:String(serial)}:e);} }
 let number='Enter a valid date and serial'; try{if(editor)number=quoteNumber(editor.date,editor.serial);}catch{}
 let preview=html; if(editor && html) {try{ const previous=new DOMParser().parseFromString(html,'text/html'); const cell=previous.querySelector('[data-quote-number]') ?? previous.querySelector('table tr:nth-child(2) td'); if(cell) cell.textContent=quoteNumber(editor.date,editor.serial);preview='<!doctype html>'+previous.documentElement.outerHTML;}catch{} }
 if(!ready)return <p>Opening local workspace…</p>;
 return <><div className="page-title"><div><p className="eyebrow">QUOTATION WORKSPACE</p><h1>Quotation Generator</h1><p className="muted">From product research to an Outlook-ready quotation.</p></div>{editor && <button className="secondary" disabled={busy} onClick={()=>{if(confirm('Start a new quotation? Unsaved edits will be discarded.')) {setEditor(null);setId(undefined);setText('');setHtml('');setError('');setMessage('');history.replaceState(null,'','/');}}}>＋ New quotation</button>}</div>
 <div className="steps"><span className={!editor?'current':''}><b>1</b> Import products</span><span className={editor?'current':''}><b>2</b> Review & prepare quotation</span></div>
 {error && <div className="alert error" role="alert">{error}</div>}{message && <div className="alert success" role="status">{message}</div>}
 {!editor ? <section className="panel import-panel"><div className="section-heading"><div><h2>Import product research</h2><p>Upload a JSON file or paste your structured product data below.</p></div><span className="tag">Schema 1.0</span></div><label className="upload"><span className="upload-icon">↥</span><strong>Choose a JSON file</strong><span>Product details stay on your device</span><input aria-label="Upload JSON file" type="file" accept=".json,application/json" onChange={e=>{const file=e.target.files?.[0];if(file)void run(async()=>{setText(await file.text());setMessage(`${file.name} loaded. Click Import Products to validate.`);});}}/></label><div className="divider">or paste JSON</div><label className="field"><span>Product JSON</span><textarea className="json" rows={12} value={text} onChange={e=>setText(e.target.value)} spellCheck={false} placeholder={'{\n  "schema_version": "1.0",\n  "products": [ … ]\n}'}/></label><div className="panel-bottom"><span className="muted">Original order, quantities and part numbers are preserved.</span><button disabled={busy || !text.trim()} onClick={()=>void run(importData)}>Import Products →</button></div></section> : <>
 <section className="panel"><div className="section-heading"><div><h2>Quotation preview</h2><p>{number} <span className={`tag ${fresh?'green':''}`}>{fresh?'Ready to copy':'Needs modification'}</span></p></div><div className="actions"><button disabled={!fresh || busy} onClick={()=>void run(async()=>{await copyQuote(html);setMessage('Formatted quotation copied. Paste it into Outlook.');})}>Copy Quotation</button><button className="secondary" disabled={!fresh || busy} onClick={()=>download(html,`${number}.html`,'text/html')}>Download HTML</button></div></div>{!fresh && <p className="notice">Enter the details below, then click Modify Template to finalize the preview.</p>}<Preview html={preview}/></section>
 <section className="panel"><div className="section-heading"><div><h2>Quotation details</h2><p>Set the customer, reference and commercial terms.</p></div><span className="tag">{id?'Editing saved quotation':'New draft'}</span></div><div className="field-grid"><Field label="Customer / Company Name" value={editor.customer} onChange={s=>change('customer',s)} hint="Required before marking as Sent"/><Field label="Customer Email (optional)" type="email" value={editor.email} onChange={s=>change('email',s)}/><Field label="Quotation Date" type="date" value={editor.date} onChange={s=>void run(()=>changeDate(s))}/><label className="field"><span>Quotation Serial Number</span><input aria-label="Quotation Serial Number" inputMode="numeric" pattern="[1-9][0-9]*" value={editor.serial} onChange={e=>{const s=e.target.value;if(s==='' || /^[1-9]\d*$/.test(s)){setManualSerial(true);change('serial',s);}}}/><small>{number}</small></label><Field label="Payment Terms" value={editor.payment} onChange={s=>change('payment',s)}/><Field label="Incoterms" value={editor.incoterms} onChange={s=>change('incoterms',s)}/><Field label="Validity" value={editor.validity} onChange={s=>change('validity',s)}/></div>{warning && <div className="alert warning">This serial has already been used in this year. A different date may be used, but a duplicate full quotation number cannot be saved.</div>}</section>
 <section className="panel"><div className="section-heading"><div><h2>Product Pricing</h2><p>Enter the purchase price per unit. Margin is applied before conversion; shipping is added once; VAT is applied to the subtotal.</p></div><span className="tag">{editor.products.length} {editor.products.length===1?'product':'products'}</span></div><div className="rates"><span><strong>Manual exchange rates</strong><small>AED per currency unit · rounded working rates, not live rates</small></span><span className="fixed-rate">AED <b>1.00</b></span>{(['USD','EUR','GBP'] as const).map(c=><Field key={c} label={`${c} → AED`} type="number" min="0" step="any" value={editor.rates[c]} onChange={s=>{const rates={...editor.rates,[c]:s};change('rates',rates);void saveRates(rates).catch(e=>setError(e.message));}}/>)}</div>
 {editor.products.map((p,i)=>{let calc:ReturnType<typeof calculateRow>|undefined;try{calc=calculateRow(p,editor.rates);}catch{}return <article className="product" key={i}><div className="product-heading"><span className="item-number">{String(i+1).padStart(2,'0')}</span><div><h3>{p.part_number}</h3><span className="muted">{p.manufacturer || 'Manufacturer not supplied'}</span></div><span className="quantity">Quantity <b>{p.quantity}</b></span><button className="product-delete" aria-label={`Delete Product ${p.part_number}`} title={editor.products.length===1?'A quotation must contain at least one product.':`Remove ${p.part_number}`} disabled={busy||editor.products.length===1} onClick={()=>remove(i)}>Delete Product</button></div><div className="product-edit"><label className="field description"><span>Description</span><textarea rows={2} value={p.description??''} onChange={e=>product(i,'description',e.target.value)}/></label><Field label="Datasheet / product-page URL" value={p.datasheet_url??''} onChange={s=>product(i,'datasheet_url',s || null)}/><Field label="Sourcing From" value={p.sourcingFrom} onChange={s=>product(i,'sourcingFrom',s)}/><Field label="Country of Origin" value={p.countryOfOrigin} onChange={s=>product(i,'countryOfOrigin',s)}/></div><div className="pricing-fields"><Field label="Unit Weight (kg)" value={p.weight} onChange={s=>product(i,'weight',s)} hint={p.weight?`Type: ${p.weight_type || 'Not supplied'}`:'Missing weight — required'}/><Field label="Unit Price" type="number" min="0" step="any" value={p.price} onChange={s=>product(i,'price',s)}/><Field label="Margin %" type="number" min="0" step="any" value={p.margin} onChange={s=>{if(s===''||/^\d+(\.\d*)?$/.test(s))product(i,'margin',s)}}/><label className="field"><span>Currency</span><select aria-label="Currency" value={p.currency} onChange={e=>product(i,'currency',e.target.value)}>{currencies.map(c=><option key={c} value={c}>{c} — {{USD:'US Dollar',EUR:'Euro',AED:'UAE Dirham',GBP:'British Pound'}[c]}</option>)}</select></label><Field label="Lead Time" value={p.leadTime} onChange={s=>product(i,'leadTime',s)} hint="Enter the confirmed lead time"/></div><dl className="calculation-strip">{[['Entered Unit Price',calc?`${calc.entered} ${p.currency}`:undefined],['Margin %',`${p.margin||'0'}%`],['Price After Margin',calc?`${calc.priceAfterMargin} ${p.currency}`:undefined],['Currency',p.currency],['Exchange Rate',calc?.rate],['Converted Unit AED',calc?.converted],['Actual Unit Weight',p.weight?`${p.weight} kg`:undefined],['Billable Weight',calc?`${calc.billableWeight} kg`:undefined],['Shipping / Unit AED',calc?.shipping],['Final Unit AED',calc?.unit],['Total AED',calc?.total],['Lead Time',p.leadTime||undefined]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value??'—'}</dd></div>)}</dl></article>;})}
 <div className="panel-bottom"><span className="muted">Shipping: AED 30/kg · each unit rounds up to the next 0.25 kg · VAT: 5%</span><div className="actions"><button disabled={busy} onClick={()=>void run(async()=>{await assertAvailable(editor,id);const totals=calculate(editor);setHtml(renderQuote(editor,totals));setFinalized(JSON.stringify(editor));setMessage('Quotation updated. Ready to copy or save.');})}>Modify Template</button><button className="secondary" disabled={!fresh || busy} onClick={()=>void run(async()=>{if(!original)return;const q=await saveQuote(editor,original,id);setId(q.id);setMessage(`Saved ${q.number} as ${q.status}. Saving does not send an email.`);history.replaceState(null,'',`/?edit=${q.id}`);})}>Save Quotation</button></div></div></section>
 </>}
 </>;
}


