'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { Backup, Quote, db, exportBackup, markSent, parseBackup, restoreBackup } from '@/lib/storage';
import { copyQuote, download } from '@/lib/clipboard';
import Preview from './Preview';
export default function History() {
 const [quotes,setQuotes]=useState<Quote[]>([]);const [search,setSearch]=useState('');const [status,setStatus]=useState('');const [date,setDate]=useState('');const [view,setView]=useState<Quote|null>(null);const [backup,setBackup]=useState<Backup|null>(null);const [error,setError]=useState('');const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);const [loading,setLoading]=useState(true);
 async function reload(){setQuotes(await db.quotes.orderBy('createdAt').reverse().toArray());}
 useEffect(()=>{reload().catch(e=>setError(e.message)).finally(()=>setLoading(false));},[]);
 useEffect(()=>{const escape=(e:KeyboardEvent)=>{if(e.key==='Escape'){setView(null);setBackup(null);}};document.addEventListener('keydown',escape);return()=>document.removeEventListener('keydown',escape);},[]);
 async function run(fn:()=>Promise<void>){setBusy(true);setError('');setMessage('');try{await fn();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const filtered=quotes.filter(q=>(!status || q.status===status)&&(!date || q.editor.date===date)&&[q.number,q.editor.customer,...q.editor.products.flatMap(p=>[p.part_number,p.manufacturer??'',p.sourcingFrom,p.countryOfOrigin])].join(' ').toLowerCase().includes(search.toLowerCase()));
 return <><div className="page-title"><div><p className="eyebrow">LOCAL ARCHIVE</p><h1>Quotation History</h1><p className="muted">Your saved quotations, kept on this device.</p></div><Link className="button" href="/">＋ New quotation</Link></div>{error&&!backup&&<div className="alert error" role="alert">{error}</div>}{message&&<div className="alert success" role="status">{message}</div>}
 <section className="panel"><div className="section-heading"><div><h2>Saved quotations <span className="count">{quotes.length}</span></h2><p>Copying or saving a quotation does not mark it as Sent.</p></div><div className="actions"><button className="secondary" disabled={busy} onClick={()=>void run(async()=>{download(JSON.stringify(await exportBackup(),null,2),`Sajith-Quote-backup-${new Date().toISOString().slice(0,10)}.json`,'application/json');})}>Export Backup</button><label className="button secondary file-button">Import Backup<input type="file" accept=".json,application/json" disabled={busy} onChange={e=>{const f=e.target.files?.[0];if(f)void run(async()=>setBackup(parseBackup(await f.text())));e.target.value='';}}/></label></div></div><div className="filters"><label className="field search"><span>Search quotations</span><input placeholder="Quote number, customer, part number or manufacturer" value={search} onChange={e=>setSearch(e.target.value)}/></label><label className="field"><span>Quotation date</span><input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label className="field"><span>Status</span><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option><option>Draft</option><option>Sent</option></select></label>{(search||date||status)&&<button className="text-button" onClick={()=>{setSearch('');setDate('');setStatus('');}}>Clear filters</button>}</div>
 <div className="table-scroll"><table className="history-table"><thead><tr>{['Quote Number','Customer','Date','Products','Grand Total','Status','Actions'].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{filtered.map(q=><tr key={q.id}><td><strong>{q.number}</strong></td><td>{q.editor.customer||'—'}</td><td>{q.editor.date}</td><td>{q.editor.products.map((p,i)=><span key={i}><strong>{p.part_number}</strong><small>Sourcing From: {p.sourcingFrom||'—'} · Country of Origin: {p.countryOfOrigin||'—'}</small></span>)}</td><td className="money">AED {q.totals.grandTotal}</td><td><span className={`tag ${q.status==='Sent'?'green':''}`}>{q.status}</span>{q.sentAt&&<small>Sent {new Date(q.sentAt).toLocaleString('en-GB',{timeZone:'Asia/Dubai'})} UAE</small>}</td><td><div className="row-actions"><button onClick={()=>setView(q)}>View</button><Link href={`/?edit=${q.id}`}>Edit</Link><button disabled={busy} onClick={()=>void run(async()=>{await copyQuote(q.html);setMessage('Formatted quotation copied.');})}>Copy</button><button onClick={()=>download(q.html,`${q.number}.html`,'text/html')}>Download HTML</button>{q.status==='Draft'&&<button disabled={busy} onClick={()=>void run(async()=>{await markSent(q.id);await reload();setMessage(`${q.number} marked as Sent.`);})}>Mark as Sent</button>}<button className="danger" disabled={busy} onClick={()=>{if(confirm(`Delete ${q.number}? Its serial number will remain reserved.`))void run(async()=>{await db.quotes.delete(q.id);await reload();setMessage('Quotation deleted. Its serial remains reserved.');});}}>Delete</button></div></td></tr>)}</tbody></table></div>{!filtered.length&&<div className="empty"><span className="empty-icon">▤</span><h3>{loading?'Loading quotations…':quotes.length?'No matching quotations':'No quotations saved yet'}</h3><p>{quotes.length?'Try a different search or filter.':'Prepare your first quotation in the generator, then save it here.'}</p>{!quotes.length&&!loading&&<Link className="button secondary" href="/">Go to Generator →</Link>}</div>}</section><p className="backup-note">Keep a copy outside this browser. Export Backup includes quotations, calculation details, reserved serial numbers and saved exchange rates.</p>
 {view&&<div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-label="Saved quotation"><div className="section-heading"><div><h2>{view.number}</h2><p>{view.status}{view.sentAt?` · Sent ${new Date(view.sentAt).toLocaleString('en-GB',{timeZone:'Asia/Dubai'})} UAE`:''}</p></div><button autoFocus className="secondary" onClick={()=>setView(null)}>Close</button></div><div className="notice"><strong>Internal product details</strong>{view.editor.products.map((p,i)=><small key={i}>{p.part_number} · Sourcing From: {p.sourcingFrom||'—'} · Country of Origin: {p.countryOfOrigin||'—'}</small>)}</div><Preview html={view.html}/></section></div>}
 {backup&&<div className="modal-backdrop"><section className="modal small-modal" role="dialog" aria-modal="true" aria-label="Restore backup"><h2>Restore local backup</h2>{error&&<div className="alert error" role="alert">{error}</div>}<p>This validated backup contains {backup.quotes.length} quotations and {backup.used.length} reserved numbers.</p><p><strong>Merge</strong> adds compatible records. Conflicting records are rejected; existing settings are retained.</p><p><strong>Replace</strong> removes all current quotations, reserved numbers and settings, then restores this backup.</p><div className="actions"><button autoFocus disabled={busy} onClick={()=>void run(async()=>{await restoreBackup(backup,false);setBackup(null);await reload();setMessage('Backup merged successfully.');})}>Merge compatible records</button><button className="danger secondary" disabled={busy} onClick={()=>{if(confirm('Replace ALL local quotations, serial reservations and settings with this backup? Export your current data first if needed.'))void run(async()=>{await restoreBackup(backup,true);setBackup(null);await reload();setMessage('Backup restored successfully.');});}}>Replace all local records</button><button className="secondary" onClick={()=>setBackup(null)}>Cancel</button></div></section></div>}
 </>;
}

