import Decimal from 'decimal.js';
import { Editor, Row, quoteNumber, safeUrl } from './model';
Decimal.set({ precision: 40, rounding: Decimal.ROUND_HALF_UP });
export function decimal(value: string, label: string, zero = false) { if (!/^\d+(\.\d+)?$/.test(value) || value.length > 24) throw new Error(`${label}: enter a valid ${zero ? 'non-negative' : 'positive'} number.`); const d = new Decimal(value); if (zero ? d.lt(0) : d.lte(0)) throw new Error(`${label}: must be ${zero ? 'zero or greater' : 'greater than zero'}.`); return d; }
export function exchangeRate(currency: Row['currency'], rates: Editor['rates']) { return currency === 'USD' ? new Decimal('3.70') : currency === 'AED' ? new Decimal(1) : decimal(rates[currency], `${currency} exchange rate`); }
export function billableWeight(weight: string) { return decimal(weight, 'Unit weight').div('0.5').ceil().mul('0.5'); }
export function calculateRow(p: Row, rates: Editor['rates']) { const rate = exchangeRate(p.currency,rates); const weight = billableWeight(p.weight); const shipping = weight.mul(30); const converted = decimal(p.price, 'Unit price', true).mul(rate); const unit = converted.plus(shipping).toDecimalPlaces(2); return { rate: rate.toString(), billableWeight: weight.toString(), converted: converted.toFixed(2), shipping: shipping.toFixed(2), totalShipping: shipping.mul(p.quantity).toFixed(2), unit: unit.toFixed(2), total: unit.mul(p.quantity).toFixed(2) }; }
export function calculate(e: Editor) { quoteNumber(e.date,e.serial); if (e.email && !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(e.email)) throw new Error('Enter a valid customer email or leave it blank.'); const rows = e.products.map((p,i) => { try { if (p.datasheet_url !== null && !safeUrl(p.datasheet_url)) throw new Error('Datasheet URL must use http:// or https://.'); if (!p.leadTime.trim()) throw new Error('Enter a lead time (the original template has no default).'); return calculateRow(p,e.rates); } catch (err) { throw new Error(`Product ${i+1} (${p.part_number}): ${(err as Error).message}`); } }); const subtotal = rows.reduce((s,r) => s.plus(r.total),new Decimal(0)); const vat = subtotal.mul('0.05').toDecimalPlaces(2); return { rows, subtotal: subtotal.toFixed(2), vat: vat.toFixed(2), grandTotal: subtotal.plus(vat).toFixed(2) }; }
export type Totals = ReturnType<typeof calculate>;
