import Dexie, { type Table } from 'dexie';
import { z } from 'zod';
import { Editor, Imported, editorSchema, importSchema, quoteNumber } from './model';
import { calculate, Totals } from './calculations';
import { renderQuote } from './render';
export type Quote = { id: string; number: string; editor: Editor; original: Imported; totals: Totals; html: string; status: 'Draft' | 'Sent'; createdAt: string; updatedAt: string; sentAt: string | null };
export type Reservation = { number: string; year: number; serial: number; owner: string };
export class QuoteDB extends Dexie { quotes!: Table<Quote,string>; used!: Table<Reservation,string>; settings!: Table<{key: string; value: Editor['rates']},string>; constructor(name = 'Sajith-Quote') { super(name); this.version(1).stores({quotes:'id,&number,createdAt',used:'number,year,serial,owner',settings:'key'}); } }
export const db = new QuoteDB();
export async function nextSerial(year: number) { const used = await db.used.where('year').equals(year).toArray(); return Math.max(0,...used.map(r => r.serial))+1; }
export async function serialWarning(e: Editor, id?: string) { return (await db.used.where('year').equals(Number(e.date.slice(0,4))).toArray()).some(r => r.serial === Number(e.serial) && r.owner !== id); }
export async function assertAvailable(e: Editor, id?: string) { const n = quoteNumber(e.date,e.serial); const used = await db.used.get(n); if (used && used.owner !== id) throw new Error('This full quotation number is already reserved. Choose another serial or date.'); }
export async function saveQuote(e: Editor, original: Imported, id?: string) { const totals = calculate(e); return db.transaction('rw',db.quotes,db.used,db.settings,async () => { await assertAvailable(e,id); const existing = id ? await db.quotes.get(id) : undefined; if(id && !existing) throw new Error('This quotation was deleted. Start a new quotation.'); const stamp = new Date().toISOString(); const q: Quote = { id: id || crypto.randomUUID(), number: quoteNumber(e.date,e.serial), editor: structuredClone(e), original, totals, html: renderQuote(e,totals), status: existing?.status ?? 'Draft', sentAt: existing?.sentAt ?? null, createdAt: existing?.createdAt ?? stamp, updatedAt: stamp }; if(q.status === 'Sent' && !e.customer.trim()) throw new Error('Customer name is required for a Sent quotation.'); await db.quotes.put(q); await db.used.put({number:q.number,year:Number(e.date.slice(0,4)),serial:Number(e.serial),owner:q.id}); await db.settings.put({key:'rates',value:e.rates}); return q; }); }
export async function markSent(id: string) { await db.transaction('rw',db.quotes,async () => { const q = await db.quotes.get(id); if(!q) throw new Error('Quotation not found.'); if(!q.editor.customer.trim()) throw new Error('Edit this quotation and enter a customer name before marking it as Sent.'); if(q.status==='Sent') return; await db.quotes.update(id,{status:'Sent',sentAt:new Date().toISOString(),updatedAt:new Date().toISOString()}); }); }
const money = z.string().regex(/^\d+\.\d{2}$/);
const totalsSchema = z.object({ rows:z.array(z.object({rate:z.string(),billableWeight:z.string(),converted:money,shipping:money,totalShipping:money,unit:money,total:money})),subtotal:money,vat:money,grandTotal:money });
const quoteSchema = z.object({id:z.string().min(1),number:z.string(),editor:editorSchema,original:importSchema,totals:totalsSchema,html:z.string(),status:z.enum(['Draft','Sent']),createdAt:z.iso.datetime(),updatedAt:z.iso.datetime(),sentAt:z.iso.datetime().nullable()});
const backupSchema = z.object({app:z.literal('Sajith-Quote'),version:z.literal(1),exportedAt:z.iso.datetime(),quotes:z.array(quoteSchema),used:z.array(z.object({number:z.string(),year:z.number().int().min(1000).max(9999),serial:z.number().int().positive().safe(),owner:z.string().min(1)})),settings:z.array(z.object({key:z.literal('rates'),value:editorSchema.shape.rates}))});
export type Backup = z.infer<typeof backupSchema>;
function canonical(value: unknown): string { if(Array.isArray(value)) return '['+value.map(canonical).join(',')+']'; if(value && typeof value==='object') return '{'+Object.entries(value).sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>JSON.stringify(k)+':'+canonical(v)).join(',')+'}'; return JSON.stringify(value); }
export async function exportBackup(): Promise<Backup> { return db.transaction('r',db.quotes,db.used,db.settings,async () => ({app:'Sajith-Quote',version:1,exportedAt:new Date().toISOString(),quotes:await db.quotes.toArray(),used:await db.used.toArray(),settings:await db.settings.toArray() as Backup['settings']})); }
export function parseBackup(text: string): Backup { const b = backupSchema.parse(JSON.parse(text)); const ids = new Set<string>(); const numbers = new Set<string>(); const reservations = new Map<string,Reservation>(); for(const r of b.used) { if(reservations.has(r.number)) throw new Error('Duplicate reservation in backup.'); if(!r.number.startsWith(`Q-ENCR${String(r.year).slice(-2)}-S${r.serial}-`) || !/^Q-ENCR\d{2}-S[1-9]\d*-\d{4}$/.test(r.number)) throw new Error('Invalid serial ledger.'); reservations.set(r.number,r); } for(const q of b.quotes) { if(ids.has(q.id) || numbers.has(q.number)) throw new Error('Duplicate quotations in backup.'); ids.add(q.id); numbers.add(q.number); const t = calculate(q.editor); if(q.number !== quoteNumber(q.editor.date,q.editor.serial) || JSON.stringify(t)!==JSON.stringify(q.totals) || q.html !== renderQuote(q.editor,t)) throw new Error('Backup quotation HTML or calculations do not match its validated data.'); const r = reservations.get(q.number); if(!r || r.owner!==q.id || r.year!==Number(q.editor.date.slice(0,4)) || r.serial!==Number(q.editor.serial)) throw new Error('Missing or inconsistent serial reservation.'); if(q.status==='Sent' && (!q.sentAt || !q.editor.customer.trim())) throw new Error('Sent quotation requires a customer and sent timestamp.'); } return b; }
export async function restoreBackup(b: Backup, replace: boolean) { b = parseBackup(JSON.stringify(b)); await db.transaction('rw',db.quotes,db.used,db.settings,async () => { if(replace) { await db.quotes.clear(); await db.used.clear(); await db.settings.clear(); } else { for(const q of b.quotes) { const existing = await db.quotes.get(q.id); const byNumber = await db.quotes.where('number').equals(q.number).first(); if((existing && canonical(existing)!==canonical(q)) || (byNumber && byNumber.id!==q.id)) throw new Error(`Merge conflict: ${q.number}. Nothing was imported.`); } for(const r of b.used) { const existing = await db.used.get(r.number); if(existing && (existing.owner!==r.owner || existing.year!==r.year || existing.serial!==r.serial)) throw new Error(`Reserved number conflict: ${r.number}. Nothing was imported.`); } } await db.quotes.bulkPut(b.quotes); await db.used.bulkPut(b.used); for(const s of b.settings) if(replace || !(await db.settings.get(s.key))) await db.settings.put(s); }); }

