import { chromium } from '@playwright/test';
import { strict as assert } from 'node:assert';
import { mkdir, rm } from 'node:fs/promises';
import { readFile } from 'node:fs/promises';
import path from 'node:path';
const profile=path.resolve('test-results/browser-profile');
await mkdir('test-results',{recursive:true});
await rm(profile,{recursive:true,force:true});
const options={channel:'msedge',headless:true,viewport:{width:1440,height:1100},permissions:['clipboard-read','clipboard-write']};
let context=await chromium.launchPersistentContext(profile,options);
let page=await context.newPage();
const errors=[];page.on('pageerror',e=>errors.push(e.message));
page.on('dialog',d=>d.accept());
const product={part_number:'S-T50',manufacturer:'Mitsubishi Electric',description:'Industrial contactor',quantity:2,unit_weight_kg:0.4,weight_type:'net',weight_source_type:'manufacturer',weight_source_url:null,datasheet_url:'https://example.com/product?x=1&y=2',document_type:'product_page',product_status:'active',verification_notes:null};
await page.goto('http://127.0.0.1:3000/');
await page.getByLabel('Product JSON').waitFor();
await page.screenshot({path:'test-results/generator-desktop.png',fullPage:true});
await page.getByLabel('Product JSON').fill('{');await page.getByRole('button',{name:'Import Products'}).click();await page.getByRole('alert').filter({hasText:'Invalid JSON'}).waitFor();
await page.getByLabel('Product JSON').fill(JSON.stringify({schema_version:'1.0',products:[product,{...product,part_number:'SECOND',quantity:1,unit_weight_kg:null}]}));
await page.getByRole('button',{name:'Import Products'}).click();
await page.getByRole('heading',{name:'Product Pricing',exact:true}).waitFor();
assert.equal(await page.locator('.product').count(),2);
assert.equal(await page.getByLabel('USD → AED').inputValue(),'3.70');assert.equal(await page.getByLabel('EUR → AED').inputValue(),'4.30');assert.equal(await page.getByLabel('GBP → AED').inputValue(),'4.90');
assert.equal(await page.getByRole('button',{name:'Copy Quotation',exact:true}).isDisabled(),true);
await page.getByRole('button',{name:'Modify Template'}).click();await page.locator('.alert.error').waitFor();
await page.getByLabel('Customer / Company Name').fill('Test customer');
await page.getByLabel('Quotation Date', {exact:true}).fill('2026-09-22');
await page.getByLabel('Quotation Serial Number').fill('3');
await page.getByLabel('Unit Price',{exact:true}).nth(0).fill('100');
await page.getByLabel('Margin %',{exact:true}).nth(0).fill('15');
await page.getByLabel('Sourcing From',{exact:true}).nth(0).fill('Siemens Germany');
await page.getByLabel('Country of Origin',{exact:true}).nth(0).fill('Germany');
await page.getByLabel('Lead Time',{exact:true}).nth(0).fill('1 week');
await page.getByLabel('Unit Price',{exact:true}).nth(1).fill('10');
await page.getByLabel('Sourcing From',{exact:true}).nth(1).fill('Local supplier');
await page.getByLabel('Country of Origin',{exact:true}).nth(1).fill('China');
await page.getByLabel('Lead Time',{exact:true}).nth(1).fill('2–3 weeks');
await page.getByRole('button',{name:'Modify Template'}).click();await page.getByRole('alert').filter({hasText:'Unit weight'}).waitFor();
await page.getByLabel('Unit Weight (kg)',{exact:true}).nth(1).fill('0.55');
await page.getByLabel('Currency',{exact:true}).nth(1).selectOption('EUR');
await page.getByLabel('USD → AED').fill('3.72');
await page.getByRole('button',{name:'Modify Template'}).click();
await page.getByRole('status').filter({hasText:'Quotation updated'}).waitFor();
const frame=page.frameLocator('iframe');assert.equal(await frame.locator('body').innerText().then(s=>s.includes('998.66')&&s.includes('ENCORE POWERS')&&s.includes('GENERAL TRADING CO LLC')&&s.includes('3/303, Al Zarrouni Building, Damascus Street,')&&s.includes('Al Qusais Industrial 2, Dubai, UAE.')&&s.includes('043581030 | 0504291823')&&s.includes('TRN:104014644900003')&&s.includes('COMMERCIAL OFFER')&&s.includes('Encore Powers General Trading Co. L.L.C')&&s.includes('Salesperson\nSajith')&&s.includes('COUNTRY OF ORIGIN\nMultiple')&&s.includes('Weight - 0.4 kg | Country of Origin - Germany')&&s.includes('Datasheet: S-T50')&&s.includes('sales5@encorepowers.com')&&s.includes('encorepowers.com')),true);assert.equal(await frame.locator('img[alt="Encore Powers icon"]').getAttribute('src').then(s=>s?.startsWith('data:image/png;base64,')),true);assert.equal(await frame.locator('body').innerText().then(s=>!s.includes('Siemens Germany')&&!s.includes('Sourcing From')&&!s.includes('Phone')),true);
assert.equal(await page.getByText('115.00 USD',{exact:true}).isVisible(),true);
await page.getByRole('button',{name:'Delete Product SECOND'}).click();
assert.equal(await page.locator('.product').count(),1);assert.equal(await page.getByRole('button',{name:'Delete Product S-T50'}).isDisabled(),true);
assert.equal(await frame.locator('body').innerText().then(s=>!s.includes('SECOND')&&s.includes('929.88')),true);
assert.equal(await page.getByRole('button',{name:'Copy Quotation',exact:true}).isDisabled(),true);
await page.getByRole('button',{name:'Modify Template'}).click();await page.getByRole('status').filter({hasText:'Quotation updated'}).waitFor();
await page.getByRole('button',{name:'Copy Quotation',exact:true}).click();await page.getByRole('status').filter({hasText:'Formatted quotation copied'}).waitFor();
const copied=await page.evaluate(async()=>{const items=await navigator.clipboard.read();return (await items[0].getType('text/html')).text();});assert(copied.includes('<table'));assert(copied.includes('929.88'));assert(copied.includes('Commercial Offer'));assert(copied.includes('Salesperson</strong><br>Sajith'));assert(copied.includes('ENCORE POWERS'));assert(copied.includes('GENERAL TRADING CO LLC'));assert(copied.includes('043581030 | 0504291823'));assert(copied.includes('TRN:104014644900003'));assert(copied.includes('Encore Powers General Trading Co. L.L.C'));assert(copied.includes('sales5@encorepowers.com'));assert(copied.includes('https://encorepowers.com/'));assert(copied.includes('data:image/png;base64,'));assert(copied.includes('S-T50 - Industrial contactor</span><br>'));assert(copied.includes('Weight - 0.4 kg | Country of Origin - Germany</span><br>'));assert(copied.includes('Datasheet: <a href="https://example.com/product?x=1&amp;y=2"'));assert(!copied.includes('Data:'));assert(!copied.includes('Siemens Germany'));assert(!copied.includes('Sourcing From'));assert(!copied.includes('Phone'));assert(!copied.includes('Mitsubishi Electric'));assert(!copied.includes('SECOND'));assert(!copied.includes('Margin'));assert(!copied.includes('115.00 USD'));assert(!copied.includes('Best regards'));assert(!copied.includes('Product Pricing'));
await page.getByLabel('Quotation Serial Number').fill('4');assert(await frame.locator('body').innerText().then(s=>s.includes('Q-ENCR26-S4-2209')));assert(await page.getByRole('button',{name:'Copy Quotation',exact:true}).isDisabled());
await page.getByRole('button',{name:'Modify Template'}).click();await page.getByRole('button',{name:'Save Quotation',exact:true}).click();await page.getByRole('status').filter({hasText:'as Draft'}).waitFor();
const htmlDownloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'Download HTML',exact:true}).click();const htmlDownload=await htmlDownloadPromise;await htmlDownload.saveAs('test-results/quotation.html');const downloadedHtml=await readFile('test-results/quotation.html','utf8');assert(downloadedHtml.includes('Commercial Offer'));assert(downloadedHtml.includes('data:image/png;base64,'));assert(downloadedHtml.includes('alt="Encore Powers icon"'));assert(downloadedHtml.includes('S-T50 - Industrial contactor</span><br>'));assert(downloadedHtml.includes('Weight - 0.4 kg | Country of Origin - Germany</span><br>'));assert(downloadedHtml.includes('Datasheet:'));assert(!downloadedHtml.includes('Data:'));assert(!downloadedHtml.includes('Siemens Germany'));assert(!downloadedHtml.includes('Sourcing From'));assert(!downloadedHtml.includes('Mitsubishi Electric'));
await page.locator('iframe').scrollIntoViewIfNeeded();
await frame.getByText('GRAND TOTAL',{exact:true}).waitFor();
await page.screenshot({path:'test-results/editor-desktop.png',fullPage:true});
await page.setViewportSize({width:390,height:844});
assert(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));
await page.screenshot({path:'test-results/editor-mobile.png',fullPage:true});
await page.setViewportSize({width:1440,height:1100});
await page.getByRole('link',{name:'History',exact:true}).click();await page.getByRole('cell',{name:'Q-ENCR26-S4-2209',exact:true}).waitFor();
assert.equal(await page.getByRole('cell',{name:/S-T50/}).isVisible(),true);assert.equal(await page.getByRole('cell',{name:/SECOND/}).count(),0);
assert.equal(await page.getByText('Sourcing From: Siemens Germany · Country of Origin: Germany',{exact:true}).isVisible(),true);
await page.getByLabel('Search quotations').fill('Mitsubishi');assert.equal(await page.locator('tbody tr').count(),1);
await page.getByRole('button',{name:'Mark as Sent',exact:true}).click();await page.getByRole('status').filter({hasText:'marked as Sent'}).waitFor();
await page.getByRole('button',{name:'View',exact:true}).click();await page.getByRole('dialog').waitFor();assert.equal(await page.getByRole('dialog').getByText('S-T50 · Sourcing From: Siemens Germany · Country of Origin: Germany',{exact:true}).isVisible(),true);const historyFrame=page.getByRole('dialog').frameLocator('iframe');const historyText=await historyFrame.locator('body').innerText();assert(historyText.includes('S-T50 - Industrial contactor\nWeight - 0.4 kg | Country of Origin - Germany\nDatasheet: S-T50'));assert(historyText.includes('COMMERCIAL OFFER'));assert(!historyText.includes('Siemens Germany'));await page.getByRole('button',{name:'Close',exact:true}).click();
await page.getByRole('link',{name:'Edit',exact:true}).click();await page.getByLabel('Quotation Serial Number').waitFor();assert.equal(await page.getByLabel('Quotation Serial Number').inputValue(),'4');assert.equal(await page.getByLabel('Sourcing From',{exact:true}).inputValue(),'Siemens Germany');assert.equal(await page.getByLabel('Country of Origin',{exact:true}).inputValue(),'Germany');
await page.getByRole('button',{name:'Modify Template'}).click();assert.equal(await page.getByLabel('Quotation Serial Number').inputValue(),'4');
await page.getByRole('link',{name:'History',exact:true}).click();await page.getByRole('cell',{name:'Q-ENCR26-S4-2209',exact:true}).waitFor();
const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'Export Backup',exact:true}).click();const backup=await downloadPromise;await backup.saveAs('test-results/backup.json');
const backupJson=JSON.parse(await readFile('test-results/backup.json','utf8'));assert.equal(backupJson.quotes[0].editor.products.length,1);assert.equal(backupJson.quotes[0].editor.products[0].sourcingFrom,'Siemens Germany');assert.equal(backupJson.quotes[0].editor.products[0].countryOfOrigin,'Germany');assert.equal(backupJson.quotes[0].editor.products[0].margin,'15');assert.equal(backupJson.quotes[0].editor.rates.USD,'3.72');assert.equal(backupJson.quotes[0].totals.rows[0].priceAfterMargin,'115.00');assert(backupJson.quotes[0].html.includes('Commercial Offer'));assert(backupJson.quotes[0].html.includes('data:image/png;base64,'));assert(backupJson.quotes[0].html.includes('alt="Encore Powers icon"'));assert(backupJson.quotes[0].html.includes('S-T50 - Industrial contactor</span><br>'));assert(backupJson.quotes[0].html.includes('Country of Origin - Germany'));assert(!backupJson.quotes[0].html.includes('Siemens Germany'));assert(!backupJson.quotes[0].html.includes('Sourcing From'));assert(!backupJson.quotes[0].html.includes('Mitsubishi Electric'));
await page.locator('.file-button input').setInputFiles('test-results/backup.json');await page.getByRole('dialog',{name:'Restore backup'}).waitFor();await page.getByRole('button',{name:'Merge compatible records'}).click();await page.getByRole('status').filter({hasText:'merged successfully'}).waitFor();
await page.screenshot({path:'test-results/history-desktop.png',fullPage:true});
await page.evaluate(()=>navigator.serviceWorker.ready.then(()=>true));
await context.close();
context=await chromium.launchPersistentContext(profile,options);page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
await page.goto('http://127.0.0.1:3000/history/');await page.getByRole('cell',{name:'Q-ENCR26-S4-2209',exact:true}).waitFor();
await context.setOffline(true);await page.reload();await page.getByRole('cell',{name:'Q-ENCR26-S4-2209',exact:true}).waitFor();
await page.getByRole('link',{name:'Generator',exact:true}).click();await page.getByLabel('Product JSON').waitFor();
await page.setViewportSize({width:390,height:844});await page.screenshot({path:'test-results/generator-mobile.png',fullPage:true});
assert(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));
await page.getByRole('link',{name:'History',exact:true}).click();await page.getByRole('cell',{name:'Q-ENCR26-S4-2209',exact:true}).waitFor();
await page.getByRole('button',{name:'Delete',exact:true}).click();await page.getByRole('heading',{name:'No quotations saved yet'}).waitFor();
await page.getByRole('link',{name:'Generator',exact:true}).click();await page.getByLabel('Product JSON').fill(JSON.stringify({schema_version:'1.0',products:[product]}));await page.getByRole('button',{name:'Import Products'}).click();await page.getByLabel('Quotation Serial Number').waitFor();assert.equal(await page.getByLabel('Quotation Serial Number').inputValue(),'5');
assert.equal(await page.getByLabel('USD → AED').inputValue(),'3.72');assert.equal(await page.getByLabel('EUR → AED').inputValue(),'4.30');assert.equal(await page.getByLabel('GBP → AED').inputValue(),'4.90');assert.equal(await page.getByLabel('Margin %').inputValue(),'0');assert.equal(await page.getByLabel('Sourcing From').inputValue(),'');assert.equal(await page.getByLabel('Country of Origin').inputValue(),'');
assert.deepEqual(errors,[]);await context.close();console.log('Browser workflow passed: fixed Encore header/contact details, product origin and datasheet output, sourcing privacy, pricing, history/edit, backup and offline navigation.');


